# Generated by Django 5.2.3 on 2025-08-10 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image_url',
            new_name='profile_image',
        ),
    ]
