# Generated by Django 5.2.3 on 2025-08-11 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_image_url_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
