# Generated by Django 5.2.5 on 2025-08-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='work_mode',
            field=models.CharField(default='hybrid', max_length=200),
            preserve_default=False,
        ),
    ]
