# Generated by Django 5.2.6 on 2025-09-12 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='updated_at',
        ),
    ]
