# Generated by Django 5.2.6 on 2025-09-15 03:03

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_listing_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
    ]
